### ISSUE TITLE
Can't import when installed via PyPi

### ISSUE THREAD

**Issue by prestwich** [summa-tx/riemann#29]
I have a poor understanding of PyPi and packaging in general. Riemann is not usable when installed via PyPi. This is why installing it that way is not recommended in the readme.

`$ pip install riemann-tx`
`python3`
```
>>> import riemann
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/james/devel/one-off/.venv/lib/python3.5/site-packages/riemann/__init__.py", line 1, in <module>
    import riemann.networks as networks
ImportError: No module named 'riemann.networks
```

**Comment by drmoog** [comment]
It has something to do with the virtual environment setup.

**Comment by drmoog** [comment]
@prestwich :
I have (on local anyway!) a fix for this. The documentation is confusing, but the master version of setup.py was written in the old distutils syntax rather than setuptools; by moving metadata (keywords, clarifiers) out of the setup() call into setup.cfg and using find_packages and include_package_data I get successful pip install and >>> import (checked with dir(riemann) to see if the functions and variables had loaded). 
Have put this in pull request #48

https://github.com/pypa/setuptools/blob/master/docs/setuptools.txt
and
https://setuptools.readthedocs.io/en/latest/setuptools.html
do have the explanation of what was wrong.
